/**
 * Firestore Security Rules Verification Suite (`firestore.rules.test.ts`)
 * Verifies that all "Dirty Dozen" adversarial payloads defined in `security_spec.md`
 * return PERMISSION_DENIED.
 */

export interface AdversarialTestCase {
  id: number;
  name: string;
  collection: string;
  docId: string;
  operation: 'create' | 'update' | 'get' | 'list' | 'delete';
  auth: { uid: string; email_verified: boolean } | null;
  payload?: Record<string, unknown>;
  expectedResult: 'PERMISSION_DENIED' | 'ALLOWED';
}

export const DIRTY_DOZEN_TESTS: AdversarialTestCase[] = [
  {
    id: 1,
    name: 'Identity Spoofing on Thread Create',
    collection: 'threads',
    docId: 'thread_1',
    operation: 'create',
    auth: { uid: 'user_A', email_verified: true },
    payload: {
      ownerId: 'user_B',
      title: 'Spoofed Thread',
      focusArea: 'all',
      customEtId: 'none',
      pinned: false,
      createdAt: 'REQUEST_TIME',
      updatedAt: 'REQUEST_TIME',
    },
    expectedResult: 'PERMISSION_DENIED',
  },
  {
    id: 2,
    name: 'Unverified Email Spoof Attack',
    collection: 'threads',
    docId: 'thread_1',
    operation: 'create',
    auth: { uid: 'user_A', email_verified: false },
    payload: {
      ownerId: 'user_A',
      title: 'Unverified User Thread',
      focusArea: 'all',
      customEtId: 'none',
      pinned: false,
      createdAt: 'REQUEST_TIME',
      updatedAt: 'REQUEST_TIME',
    },
    expectedResult: 'PERMISSION_DENIED',
  },
  {
    id: 3,
    name: 'Shadow Field Injection on Thread Update',
    collection: 'threads',
    docId: 'thread_1',
    operation: 'update',
    auth: { uid: 'user_A', email_verified: true },
    payload: {
      ownerId: 'user_A',
      title: 'Updated Title',
      focusArea: 'all',
      customEtId: 'none',
      pinned: true,
      isAdmin: true,
      createdAt: 'EXISTING_TIME',
      updatedAt: 'REQUEST_TIME',
    },
    expectedResult: 'PERMISSION_DENIED',
  },
  {
    id: 4,
    name: 'Orphaned Message Write to Non-Existent Thread',
    collection: 'messages',
    docId: 'msg_1',
    operation: 'create',
    auth: { uid: 'user_A', email_verified: true },
    payload: {
      ownerId: 'user_A',
      threadId: 'non_existent_thread',
      role: 'user',
      content: 'Hello',
      focusArea: 'all',
      sourcesText: '',
      msgTimestamp: 1700000000000,
      createdAt: 'REQUEST_TIME',
      updatedAt: 'REQUEST_TIME',
    },
    expectedResult: 'PERMISSION_DENIED',
  },
  {
    id: 5,
    name: 'ID Poisoning with Invalid Characters',
    collection: 'memories',
    docId: 'invalid$id!@#',
    operation: 'create',
    auth: { uid: 'user_A', email_verified: true },
    payload: {
      ownerId: 'user_A',
      category: 'business',
      content: 'Valid content',
      createdAt: 'REQUEST_TIME',
      updatedAt: 'REQUEST_TIME',
    },
    expectedResult: 'PERMISSION_DENIED',
  },
  {
    id: 6,
    name: 'Denial-of-Wallet Oversized String Payload',
    collection: 'memories',
    docId: 'mem_1',
    operation: 'create',
    auth: { uid: 'user_A', email_verified: true },
    payload: {
      ownerId: 'user_A',
      category: 'business',
      content: 'A'.repeat(5000),
      createdAt: 'REQUEST_TIME',
      updatedAt: 'REQUEST_TIME',
    },
    expectedResult: 'PERMISSION_DENIED',
  },
  {
    id: 7,
    name: 'Immutable createdAt Field Tampering on Update',
    collection: 'threads',
    docId: 'thread_1',
    operation: 'update',
    auth: { uid: 'user_A', email_verified: true },
    payload: {
      ownerId: 'user_A',
      title: 'Tampered Timestamp',
      focusArea: 'all',
      customEtId: 'none',
      pinned: false,
      createdAt: 'NEW_FORGED_TIME',
      updatedAt: 'REQUEST_TIME',
    },
    expectedResult: 'PERMISSION_DENIED',
  },
  {
    id: 8,
    name: 'Client Timestamp Forgery on CustomET Create',
    collection: 'customEts',
    docId: 'et_1',
    operation: 'create',
    auth: { uid: 'user_A', email_verified: true },
    payload: {
      ownerId: 'user_A',
      name: 'Forged Time ET',
      tagline: 'Tagline',
      instructions: 'Instructions',
      focusArea: 'gos',
      color: 'from-cyan-500 to-teal-500',
      knowledgeText: '',
      knowledgeFileNames: '',
      createdAt: '2020-01-01T00:00:00Z',
      updatedAt: 'REQUEST_TIME',
    },
    expectedResult: 'PERMISSION_DENIED',
  },
  {
    id: 9,
    name: 'Cross-Tenant Document Get Request',
    collection: 'customEts',
    docId: 'et_owned_by_user_A',
    operation: 'get',
    auth: { uid: 'user_B', email_verified: true },
    expectedResult: 'PERMISSION_DENIED',
  },
  {
    id: 10,
    name: 'Unfiltered Cross-Tenant List Query',
    collection: 'memories',
    docId: '*',
    operation: 'list',
    auth: { uid: 'user_B', email_verified: true },
    expectedResult: 'PERMISSION_DENIED',
  },
  {
    id: 11,
    name: 'Enum Category Violation on MemoryItem',
    collection: 'memories',
    docId: 'mem_1',
    operation: 'create',
    auth: { uid: 'user_A', email_verified: true },
    payload: {
      ownerId: 'user_A',
      category: 'unauthorized_category',
      content: 'Fact',
      createdAt: 'REQUEST_TIME',
      updatedAt: 'REQUEST_TIME',
    },
    expectedResult: 'PERMISSION_DENIED',
  },
  {
    id: 12,
    name: 'Value Poisoning on Whitelisted Update Key',
    collection: 'threads',
    docId: 'thread_1',
    operation: 'update',
    auth: { uid: 'user_A', email_verified: true },
    payload: {
      ownerId: 'user_A',
      title: 'Valid Title',
      focusArea: 'all',
      customEtId: 'none',
      pinned: 'not_a_boolean',
      createdAt: 'EXISTING_TIME',
      updatedAt: 'REQUEST_TIME',
    },
    expectedResult: 'PERMISSION_DENIED',
  },
];
